# coding: utf-8

"""
    Tortoise Merchant API

    Tortoise API for merchant to integrate with their existing systems   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@tortoise.pro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scheme_api import SchemeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSchemeApi(unittest.TestCase):
    """SchemeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.scheme_api.SchemeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_scheme(self):
        """Test case for add_scheme

        Add a new scheme  # noqa: E501
        """
        pass

    def test_edit_scheme(self):
        """Test case for edit_scheme

        Edit scheme details  # noqa: E501
        """
        pass

    def test_fetch_all_schemes(self):
        """Test case for fetch_all_schemes

        Fetch all schemes  # noqa: E501
        """
        pass

    def test_get_scheme(self):
        """Test case for get_scheme

        Get scheme by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
