# coding: utf-8

"""
    Tortoise Merchant API

    Tortoise API for merchant to integrate with their existing systems   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@tortoise.pro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cancellation_api import CancellationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCancellationApi(unittest.TestCase):
    """CancellationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cancellation_api.CancellationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_cancellation(self):
        """Test case for add_cancellation

        Create a new cancellation request for a plan  # noqa: E501
        """
        pass

    def test_edit_cancellation(self):
        """Test case for edit_cancellation

        Edit a cancellation request for a plan  # noqa: E501
        """
        pass

    def test_fetch_all_cancellations(self):
        """Test case for fetch_all_cancellations

        Fetch all cancellations  # noqa: E501
        """
        pass

    def test_get_cancellation(self):
        """Test case for get_cancellation

        Get cancellation by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
