# coding: utf-8

"""
    Tortoise Merchant API

    Tortoise API for merchant to integrate with their existing systems   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@tortoise.pro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.redemption_api import RedemptionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRedemptionApi(unittest.TestCase):
    """RedemptionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.redemption_api.RedemptionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_redemption(self):
        """Test case for add_redemption

        Create a new redemption request for a plan  # noqa: E501
        """
        pass

    def test_edit_redemption(self):
        """Test case for edit_redemption

        Edit a redemption request for a plan  # noqa: E501
        """
        pass

    def test_fetch_all_redemptions(self):
        """Test case for fetch_all_redemptions

        Fetch all redemption requests  # noqa: E501
        """
        pass

    def test_get_redemption(self):
        """Test case for get_redemption

        Get a redemption request by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
