# coding: utf-8

"""
    Tortoise Merchant API

    Tortoise API for merchant to integrate with their existing systems   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@tortoise.pro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.redemption import Redemption  # noqa: E501
from swagger_client.rest import ApiException


class TestRedemption(unittest.TestCase):
    """Redemption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedemption(self):
        """Test Redemption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.redemption.Redemption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
