# coding: utf-8

"""
    Tortoise Merchant API

    Tortoise API for merchant to integrate with their existing systems   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@tortoise.pro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Cancellation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'plan': 'Plan',
        'request_raised_on': 'datetime',
        'request_processed_on': 'datetime',
        'status': 'str'
    }

    attribute_map = {
        'id': 'id',
        'plan': 'plan',
        'request_raised_on': 'requestRaisedOn',
        'request_processed_on': 'requestProcessedOn',
        'status': 'status'
    }

    def __init__(self, id=None, plan=None, request_raised_on=None, request_processed_on=None, status=None):  # noqa: E501
        """Cancellation - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._plan = None
        self._request_raised_on = None
        self._request_processed_on = None
        self._status = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if plan is not None:
            self.plan = plan
        if request_raised_on is not None:
            self.request_raised_on = request_raised_on
        if request_processed_on is not None:
            self.request_processed_on = request_processed_on
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this Cancellation.  # noqa: E501

        Unique identifier for the cancellation request  # noqa: E501

        :return: The id of this Cancellation.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Cancellation.

        Unique identifier for the cancellation request  # noqa: E501

        :param id: The id of this Cancellation.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def plan(self):
        """Gets the plan of this Cancellation.  # noqa: E501


        :return: The plan of this Cancellation.  # noqa: E501
        :rtype: Plan
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this Cancellation.


        :param plan: The plan of this Cancellation.  # noqa: E501
        :type: Plan
        """

        self._plan = plan

    @property
    def request_raised_on(self):
        """Gets the request_raised_on of this Cancellation.  # noqa: E501


        :return: The request_raised_on of this Cancellation.  # noqa: E501
        :rtype: datetime
        """
        return self._request_raised_on

    @request_raised_on.setter
    def request_raised_on(self, request_raised_on):
        """Sets the request_raised_on of this Cancellation.


        :param request_raised_on: The request_raised_on of this Cancellation.  # noqa: E501
        :type: datetime
        """

        self._request_raised_on = request_raised_on

    @property
    def request_processed_on(self):
        """Gets the request_processed_on of this Cancellation.  # noqa: E501


        :return: The request_processed_on of this Cancellation.  # noqa: E501
        :rtype: datetime
        """
        return self._request_processed_on

    @request_processed_on.setter
    def request_processed_on(self, request_processed_on):
        """Sets the request_processed_on of this Cancellation.


        :param request_processed_on: The request_processed_on of this Cancellation.  # noqa: E501
        :type: datetime
        """

        self._request_processed_on = request_processed_on

    @property
    def status(self):
        """Gets the status of this Cancellation.  # noqa: E501


        :return: The status of this Cancellation.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Cancellation.


        :param status: The status of this Cancellation.  # noqa: E501
        :type: str
        """
        allowed_values = ["raised", "processing", "refundInitiated", "successful", "cancelled", "failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Cancellation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Cancellation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
