# coding: utf-8

"""
    Tortoise Merchant API

    Tortoise API for merchant to integrate with their existing systems   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@tortoise.pro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Payment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'plan': 'Plan',
        'instalment_id': 'int',
        'mode': 'str',
        'amount': 'int',
        'created_on': 'datetime',
        'status': 'str'
    }

    attribute_map = {
        'id': 'id',
        'plan': 'plan',
        'instalment_id': 'instalmentId',
        'mode': 'mode',
        'amount': 'amount',
        'created_on': 'createdOn',
        'status': 'status'
    }

    def __init__(self, id=None, plan=None, instalment_id=None, mode=None, amount=None, created_on=None, status=None):  # noqa: E501
        """Payment - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._plan = None
        self._instalment_id = None
        self._mode = None
        self._amount = None
        self._created_on = None
        self._status = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if plan is not None:
            self.plan = plan
        if instalment_id is not None:
            self.instalment_id = instalment_id
        if mode is not None:
            self.mode = mode
        if amount is not None:
            self.amount = amount
        if created_on is not None:
            self.created_on = created_on
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this Payment.  # noqa: E501

        Unique identifier for the payment  # noqa: E501

        :return: The id of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Payment.

        Unique identifier for the payment  # noqa: E501

        :param id: The id of this Payment.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def plan(self):
        """Gets the plan of this Payment.  # noqa: E501


        :return: The plan of this Payment.  # noqa: E501
        :rtype: Plan
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this Payment.


        :param plan: The plan of this Payment.  # noqa: E501
        :type: Plan
        """

        self._plan = plan

    @property
    def instalment_id(self):
        """Gets the instalment_id of this Payment.  # noqa: E501

        Instalment serial number for which the payment has been made  # noqa: E501

        :return: The instalment_id of this Payment.  # noqa: E501
        :rtype: int
        """
        return self._instalment_id

    @instalment_id.setter
    def instalment_id(self, instalment_id):
        """Sets the instalment_id of this Payment.

        Instalment serial number for which the payment has been made  # noqa: E501

        :param instalment_id: The instalment_id of this Payment.  # noqa: E501
        :type: int
        """

        self._instalment_id = instalment_id

    @property
    def mode(self):
        """Gets the mode of this Payment.  # noqa: E501

        Mode of payment  # noqa: E501

        :return: The mode of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this Payment.

        Mode of payment  # noqa: E501

        :param mode: The mode of this Payment.  # noqa: E501
        :type: str
        """
        allowed_values = ["debit", "credit", "upi", "netbanking", "cash"]  # noqa: E501
        if mode not in allowed_values:
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    @property
    def amount(self):
        """Gets the amount of this Payment.  # noqa: E501

        Amount paid on the payment  # noqa: E501

        :return: The amount of this Payment.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Payment.

        Amount paid on the payment  # noqa: E501

        :param amount: The amount of this Payment.  # noqa: E501
        :type: int
        """

        self._amount = amount

    @property
    def created_on(self):
        """Gets the created_on of this Payment.  # noqa: E501

        Timestamp at which the payment has been made  # noqa: E501

        :return: The created_on of this Payment.  # noqa: E501
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this Payment.

        Timestamp at which the payment has been made  # noqa: E501

        :param created_on: The created_on of this Payment.  # noqa: E501
        :type: datetime
        """

        self._created_on = created_on

    @property
    def status(self):
        """Gets the status of this Payment.  # noqa: E501

        Status of the payment  # noqa: E501

        :return: The status of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Payment.

        Status of the payment  # noqa: E501

        :param status: The status of this Payment.  # noqa: E501
        :type: str
        """
        allowed_values = ["successful", "failed", "refunded", "refundInitiated", "processing"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Payment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Payment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
