# coding: utf-8

"""
    Tortoise Merchant API

    Tortoise API for merchant to integrate with their existing systems   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@tortoise.pro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SchemeRedemptionOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_month': 'int',
        'start_date': 'int'
    }

    attribute_map = {
        'start_month': 'startMonth',
        'start_date': 'startDate'
    }

    def __init__(self, start_month=None, start_date=None):  # noqa: E501
        """SchemeRedemptionOption - a model defined in Swagger"""  # noqa: E501

        self._start_month = None
        self._start_date = None
        self.discriminator = None

        if start_month is not None:
            self.start_month = start_month
        if start_date is not None:
            self.start_date = start_date

    @property
    def start_month(self):
        """Gets the start_month of this SchemeRedemptionOption.  # noqa: E501

        month after which the redemption can be applied  # noqa: E501

        :return: The start_month of this SchemeRedemptionOption.  # noqa: E501
        :rtype: int
        """
        return self._start_month

    @start_month.setter
    def start_month(self, start_month):
        """Sets the start_month of this SchemeRedemptionOption.

        month after which the redemption can be applied  # noqa: E501

        :param start_month: The start_month of this SchemeRedemptionOption.  # noqa: E501
        :type: int
        """

        self._start_month = start_month

    @property
    def start_date(self):
        """Gets the start_date of this SchemeRedemptionOption.  # noqa: E501

        date in the above month after which the redemption can be applied  # noqa: E501

        :return: The start_date of this SchemeRedemptionOption.  # noqa: E501
        :rtype: int
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this SchemeRedemptionOption.

        date in the above month after which the redemption can be applied  # noqa: E501

        :param start_date: The start_date of this SchemeRedemptionOption.  # noqa: E501
        :type: int
        """

        self._start_date = start_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SchemeRedemptionOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SchemeRedemptionOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
